Specify myconfig in training
autorope/donkeycar pull request #997
Opened 2022-03-15 21:57 UTC by DocGarbanzo

# Enable myconfig.py selection
When training from the command line using `donkey train` we can now add a path to a different `myconfg.py` file. This was reported as issue #976.

2022-03-16 17:08 UTC, Ezward requested changes
Look like we dropped some functionality in the calibration command.

2022-03-16 21:32 UTC, DocGarbanzo commented on donkeycar/config.py
> -    if hasattr(cfg, 'IMAGE_H') and hasattr(cfg, 'IMAGE_W'):
These config variables are not used.

2022-03-16 21:39 UTC, DocGarbanzo commented on donkeycar/management/base.py
> -        parser.add_argument(
Thanks for spotting this, this is a mistake coming from my rebase, reverted that change.

2022-03-16 21:40 UTC, DocGarbanzo commented on donkeycar/management/base.py
> -        elif args.pwm_pin is not None:
Similar error, coming from bad rebase, reverted this.

2022-03-28 04:16 UTC, Ezward approved these changes
This look good.  Thanks.

2022-04-04 20:55 UTC, merged